require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Incidents::DatIncidentsController do

  # This should return the minimal set of attributes required to create a valid
  # Incidents::DatIncident. As you add validations to Incidents::DatIncident, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Incidents::DatIncidentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all incidents_dat_incidents as @incidents_dat_incidents" do
      dat_incident = Incidents::DatIncident.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incidents_dat_incidents).should eq([dat_incident])
    end
  end

  describe "GET show" do
    it "assigns the requested incidents_dat_incident as @incidents_dat_incident" do
      dat_incident = Incidents::DatIncident.create! valid_attributes
      get :show, {:id => dat_incident.to_param}, valid_session
      assigns(:incidents_dat_incident).should eq(dat_incident)
    end
  end

  describe "GET new" do
    it "assigns a new incidents_dat_incident as @incidents_dat_incident" do
      get :new, {}, valid_session
      assigns(:incidents_dat_incident).should be_a_new(Incidents::DatIncident)
    end
  end

  describe "GET edit" do
    it "assigns the requested incidents_dat_incident as @incidents_dat_incident" do
      dat_incident = Incidents::DatIncident.create! valid_attributes
      get :edit, {:id => dat_incident.to_param}, valid_session
      assigns(:incidents_dat_incident).should eq(dat_incident)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Incidents::DatIncident" do
        expect {
          post :create, {:incidents_dat_incident => valid_attributes}, valid_session
        }.to change(Incidents::DatIncident, :count).by(1)
      end

      it "assigns a newly created incidents_dat_incident as @incidents_dat_incident" do
        post :create, {:incidents_dat_incident => valid_attributes}, valid_session
        assigns(:incidents_dat_incident).should be_a(Incidents::DatIncident)
        assigns(:incidents_dat_incident).should be_persisted
      end

      it "redirects to the created incidents_dat_incident" do
        post :create, {:incidents_dat_incident => valid_attributes}, valid_session
        response.should redirect_to(Incidents::DatIncident.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incidents_dat_incident as @incidents_dat_incident" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::DatIncident.any_instance.stub(:save).and_return(false)
        post :create, {:incidents_dat_incident => {  }}, valid_session
        assigns(:incidents_dat_incident).should be_a_new(Incidents::DatIncident)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::DatIncident.any_instance.stub(:save).and_return(false)
        post :create, {:incidents_dat_incident => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incidents_dat_incident" do
        dat_incident = Incidents::DatIncident.create! valid_attributes
        # Assuming there are no other incidents_dat_incidents in the database, this
        # specifies that the Incidents::DatIncident created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Incidents::DatIncident.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => dat_incident.to_param, :incidents_dat_incident => { "these" => "params" }}, valid_session
      end

      it "assigns the requested incidents_dat_incident as @incidents_dat_incident" do
        dat_incident = Incidents::DatIncident.create! valid_attributes
        put :update, {:id => dat_incident.to_param, :incidents_dat_incident => valid_attributes}, valid_session
        assigns(:incidents_dat_incident).should eq(dat_incident)
      end

      it "redirects to the incidents_dat_incident" do
        dat_incident = Incidents::DatIncident.create! valid_attributes
        put :update, {:id => dat_incident.to_param, :incidents_dat_incident => valid_attributes}, valid_session
        response.should redirect_to(dat_incident)
      end
    end

    describe "with invalid params" do
      it "assigns the incidents_dat_incident as @incidents_dat_incident" do
        dat_incident = Incidents::DatIncident.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::DatIncident.any_instance.stub(:save).and_return(false)
        put :update, {:id => dat_incident.to_param, :incidents_dat_incident => {  }}, valid_session
        assigns(:incidents_dat_incident).should eq(dat_incident)
      end

      it "re-renders the 'edit' template" do
        dat_incident = Incidents::DatIncident.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::DatIncident.any_instance.stub(:save).and_return(false)
        put :update, {:id => dat_incident.to_param, :incidents_dat_incident => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incidents_dat_incident" do
      dat_incident = Incidents::DatIncident.create! valid_attributes
      expect {
        delete :destroy, {:id => dat_incident.to_param}, valid_session
      }.to change(Incidents::DatIncident, :count).by(-1)
    end

    it "redirects to the incidents_dat_incidents list" do
      dat_incident = Incidents::DatIncident.create! valid_attributes
      delete :destroy, {:id => dat_incident.to_param}, valid_session
      response.should redirect_to(incidents_dat_incidents_url)
    end
  end

end
