require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Incidents::IncidentsController do

  # This should return the minimal set of attributes required to create a valid
  # Incidents::Incident. As you add validations to Incidents::Incident, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "chapter" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Incidents::IncidentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all incidents_incidents as @incidents_incidents" do
      incident = Incidents::Incident.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incidents_incidents).should eq([incident])
    end
  end

  describe "GET show" do
    it "assigns the requested incidents_incident as @incidents_incident" do
      incident = Incidents::Incident.create! valid_attributes
      get :show, {:id => incident.to_param}, valid_session
      assigns(:incidents_incident).should eq(incident)
    end
  end

  describe "GET new" do
    it "assigns a new incidents_incident as @incidents_incident" do
      get :new, {}, valid_session
      assigns(:incidents_incident).should be_a_new(Incidents::Incident)
    end
  end

  describe "GET edit" do
    it "assigns the requested incidents_incident as @incidents_incident" do
      incident = Incidents::Incident.create! valid_attributes
      get :edit, {:id => incident.to_param}, valid_session
      assigns(:incidents_incident).should eq(incident)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Incidents::Incident" do
        expect {
          post :create, {:incidents_incident => valid_attributes}, valid_session
        }.to change(Incidents::Incident, :count).by(1)
      end

      it "assigns a newly created incidents_incident as @incidents_incident" do
        post :create, {:incidents_incident => valid_attributes}, valid_session
        assigns(:incidents_incident).should be_a(Incidents::Incident)
        assigns(:incidents_incident).should be_persisted
      end

      it "redirects to the created incidents_incident" do
        post :create, {:incidents_incident => valid_attributes}, valid_session
        response.should redirect_to(Incidents::Incident.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incidents_incident as @incidents_incident" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::Incident.any_instance.stub(:save).and_return(false)
        post :create, {:incidents_incident => { "chapter" => "invalid value" }}, valid_session
        assigns(:incidents_incident).should be_a_new(Incidents::Incident)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::Incident.any_instance.stub(:save).and_return(false)
        post :create, {:incidents_incident => { "chapter" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incidents_incident" do
        incident = Incidents::Incident.create! valid_attributes
        # Assuming there are no other incidents_incidents in the database, this
        # specifies that the Incidents::Incident created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Incidents::Incident.any_instance.should_receive(:update).with({ "chapter" => "" })
        put :update, {:id => incident.to_param, :incidents_incident => { "chapter" => "" }}, valid_session
      end

      it "assigns the requested incidents_incident as @incidents_incident" do
        incident = Incidents::Incident.create! valid_attributes
        put :update, {:id => incident.to_param, :incidents_incident => valid_attributes}, valid_session
        assigns(:incidents_incident).should eq(incident)
      end

      it "redirects to the incidents_incident" do
        incident = Incidents::Incident.create! valid_attributes
        put :update, {:id => incident.to_param, :incidents_incident => valid_attributes}, valid_session
        response.should redirect_to(incident)
      end
    end

    describe "with invalid params" do
      it "assigns the incidents_incident as @incidents_incident" do
        incident = Incidents::Incident.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::Incident.any_instance.stub(:save).and_return(false)
        put :update, {:id => incident.to_param, :incidents_incident => { "chapter" => "invalid value" }}, valid_session
        assigns(:incidents_incident).should eq(incident)
      end

      it "re-renders the 'edit' template" do
        incident = Incidents::Incident.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incidents::Incident.any_instance.stub(:save).and_return(false)
        put :update, {:id => incident.to_param, :incidents_incident => { "chapter" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incidents_incident" do
      incident = Incidents::Incident.create! valid_attributes
      expect {
        delete :destroy, {:id => incident.to_param}, valid_session
      }.to change(Incidents::Incident, :count).by(-1)
    end

    it "redirects to the incidents_incidents list" do
      incident = Incidents::Incident.create! valid_attributes
      delete :destroy, {:id => incident.to_param}, valid_session
      response.should redirect_to(incidents_incidents_url)
    end
  end

end
